# Numpy

From https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-an-array-from-existing-data

In [1]:
import numpy as np

## Create a basic array

In [2]:
# 1D array
np.array([1,2,3])
# 2D array
np.array([[1,3,4],[5,3,1]])

np.zeros(2)
np.ones(2)
np.arange(2, 9, 2)
np.empty(4)
np.linspace(2,5, num=5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

## Adding, removing, and sorting elements

In [3]:
arr = np.array([1,5,3,9,4,8,2])
np.sort(arr)

array([1, 2, 3, 4, 5, 8, 9])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Shape and size of an array

In [5]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         [[0 ,1 ,2, 3],
                          [4, 5, 6, 7]]])

array_example.ndim
array_example.size
array_example.shape


(3, 2, 4)

In [6]:
a.reshape(-1, 2)

array([[1, 2],
       [3, 4]])

## How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [8]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

## Indexing and slicing

In [9]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [10]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [11]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [13]:
data.max()
data.min()
data.sum()

21

## How to create an array from existing data

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
                   [4, 4]])

np.vstack((a1, a2))
np.hstack((a1, a2))

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
np.hsplit(x, 3)
np.hsplit(x, (3, 4))